version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    build: .
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=friendship_store.settings

    volumes:
      - .:/usr/src/friendship_store/
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
      - mailhog
  celery:
    build: ./
    privileged: true
    command: celery -A friendship_store worker --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: 'friendship_store.settings'
    depends_on:
      - web
      - redis

volumes:
  data: