# Generated by Django 4.2.1 on 2023-05-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='friendship_app.product'),
        ),
    ]
