# Generated by Django 4.2.1 on 2023-05-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='user',
        ),
    ]
