# Generated by Django 4.2.1 on 2023-05-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0004_rename_favorites_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='friendship_app.product', unique=True),
        ),
    ]
