# Generated by Django 4.2.1 on 2023-05-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
