# Generated by Django 4.2.1 on 2023-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0007_alter_user_managers_rename_email_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@mail.ru', max_length=254, unique=True),
        ),
    ]
