# Generated by Django 4.2.1 on 2023-05-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0011_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.URLField(),
        ),
    ]
