# Generated by Django 4.2.1 on 2023-05-16 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship_app', '0013_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('main_image', models.URLField()),
                ('date', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('body', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
