# Generated by Django 4.2.1 on 2023-05-16 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0014_news_brand_image_product_main_image_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='friendship_app.product'),
        ),
    ]
